InventoryManager/baixa/urls.py
from django.urls import path
from . import views

app_name = 'baixa'
urlpatterns = [
path('log/', views.BaixaView.as_view(), name='log'),
path('produto/<int:pk>/',views.baixa_produto, name='baixa'),
]

InventoryManager/entrada/urls.py
from django.urls import path
from . import views

app_name = 'entrada'
urlpatterns = [
	path('log/', views.EntradaLogView.as_view(), name = 'log'),
	path('produto/<int:pk>/', views.entrada_produto, name = 'entrada')
]

InventoryManager/produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'
urlpatterns = [
	path('list/', views.ProdutoView.as_view(), name = 'list'),
	
]

InventoryManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('entrada/',include('InventoryManager.entrada.urls')),
	path('baixa/',include('InventoryManager.baixa.urls')),
	path('produto/', include('InventoryManager.produto.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InventoryManager/baixa/models.py
from django.db import models
from InventoryManager.produto.models import Produto
from django.contrib.auth.models import User

class Baixa(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE,null=True)
	baixa_data = models.DateTimeField(auto_now=True,verbose_name='Data')
	baixa_produto = models.ForeignKey(Produto, on_delete = models.CASCADE, verbose_name='Baixa')
	baixa_quantidade = models.IntegerField(verbose_name='Quantidade')
	baixa_motivo = models.TextField(verbose_name='Motivo')

	def __str__(self):
		return str(self.baixa_produto)

InventoryManager/core/models.py
from django.db import models

# Create your models here.

InventoryManager/entrada/models.py
from django.db import models
from InventoryManager.produto.models import Produto
from django.contrib.auth.models import User

class Entrada(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	entrada_produto = models.ForeignKey(Produto, on_delete = models.CASCADE, verbose_name='Produto')
	entrada_data = models.DateTimeField(auto_now=True)
	entrada_quantidade = models.IntegerField()
	entrada_motivo = models.TextField()

	def __str__(self):
		return self.entrada_produto

InventoryManager/fornecedor/models.py
from django.db import models

class Fornecedor(models.Model):
	fornecedor_nome = models.CharField('Fornecedor',max_length=100)

	def __str__(self):
		return self.fornecedor_nome

InventoryManager/produto/models.py
from django.db import models
from InventoryManager.fornecedor.models import Fornecedor

class Produto(models.Model):
	produto_fornecedor = models.ForeignKey(Fornecedor, on_delete = models.CASCADE, verbose_name='Fornecedor')
	produto_nome = models.CharField('Produto', max_length=100)
	produto_preco = models.FloatField(null=True)
	produto_quantidade = models.IntegerField()
	produto_descricao = models.TextField(null=True)
	produto_imagem = models.ImageField(upload_to='produtos/%Y/%m',null=True)


	def __str__(self):
		return self.produto_nome

InventoryManager/baixa/forms.py
from django import forms
from .models import Baixa
from django.forms.widgets import HiddenInput

class BaixaForm(forms.ModelForm):
	class Meta:
		model = Baixa
		fields = '__all__'
		widgets = {'user':forms.HiddenInput()}

InventoryManager/entrada/forms.py
from django import forms
from .models import Entrada
from django.forms.widgets import HiddenInput
class EntradaForm(forms.ModelForm):
	class Meta:
		model = Entrada
		fields = '__all__'
		widgets = {'user':forms.HiddenInput()}

InventoryManager/baixa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from InventoryManager.produto.models import Produto
from django.views.generic.list import ListView
from .forms import BaixaForm
from .models import Baixa
from django.contrib import messages

class BaixaView(ListView):
	model = Baixa
	template_name = 'baixa_log.html'
	context_object_name = 'objects'
	ordering = '-baixa_data'

def baixa_produto(request,pk):
	prod = get_object_or_404(Produto, pk=pk)
	form = BaixaForm()
	if not request.user.is_authenticated:
		messages.error(request, 'Voce precisa estar logado para realizar esta operacao')
		return redirect('produto:list')

	if request.method == 'POST':
		form = BaixaForm(request.POST or None, instance=prod)
		if form.is_valid():
			dados = Baixa(
				user = request.user,
				baixa_produto = form.cleaned_data['baixa_produto'],
				baixa_quantidade = form.cleaned_data['baixa_quantidade'],
				baixa_motivo = form.cleaned_data['baixa_motivo'],
				
				)
			
			if not dados.baixa_quantidade:
				dados.baixa_quantidade = 0
			if dados.baixa_quantidade == 0:
				messages.success(request,'Baixa igual a 0')
			if dados.baixa_quantidade < 0:
				messages.error(request, 'Valor da baixa nao pode ser menor que 0')
				return render(request, 'baixa_produto.html', {'form':form, 'produto':prod})
			if int(dados.baixa_quantidade) > prod.produto_quantidade:
				messages.error(request, 'Quantidade em estoque insuficiente')
				return render(request,'baixa_produto.html', {'form':form, 'produto':prod})
			prod.produto_quantidade -= int(dados.baixa_quantidade)
			dados.save()
			prod.save()
			messages.success(request, 'Baixa realizada com sucesso')
			return redirect('produto:list')
	else:
		return render(request,'baixa_produto.html', {'form':form, 'produto':prod})

InventoryManager/core/views.py
from django.shortcuts import render

# Create your views here.

InventoryManager/entrada/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Entrada
from .forms import EntradaForm
from django.views.generic.list import ListView
from InventoryManager.produto.models import Produto
from django.contrib import messages

class EntradaLogView(ListView):
	template_name = 'entrada_log.html'
	model = Entrada
	context_object_name = 'objects'
	ordering = '-entrada_data'


def entrada_produto(request, pk):
	prod = get_object_or_404(Produto, pk = pk)
	form = EntradaForm()
	

	if request.method == 'POST':
		form = EntradaForm(request.POST or None, instance = prod)
		if form.is_valid():
			dados = Entrada(
				user =request.user,
				entrada_produto = form.cleaned_data['entrada_produto'],
				entrada_quantidade = form.cleaned_data['entrada_quantidade'],
				entrada_motivo = form.cleaned_data['entrada_motivo'])
			if not dados.entrada_quantidade:
				dados.entrada_quantidade = 0
			if int(dados.entrada_quantidade) < 0:
				messages.error(request,'Valor da entrada nao pode ser menor que 0')
				return render(request, 'entrada_produto.html',{'form':form, 'produto':prod})
			prod.produto_quantidade += int(dados.entrada_quantidade)
			print(f'depois {prod.produto_quantidade}')
			prod.save()
			dados.save()
			messages.success(request,'Entrada do produto foi realizada com sucesso')
			return redirect('produto:list')
	else:
		return render(request, 'entrada_produto.html',{'form':form, 'produto':prod})

InventoryManager/fornecedor/views.py
from django.shortcuts import render

# Create your views here.

InventoryManager/produto/views.py
from django.shortcuts import render,redirect,get_object_or_404
from . models import Produto
from InventoryManager.baixa.models import Baixa
from InventoryManager.baixa.forms import BaixaForm
from django.views.generic.list import ListView

class ProdutoView(ListView):
	template_name = 'produto_list.html'
	context_object_name = 'objects'
	model = Produto

InventoryManager/baixa/templates/baixa_log.html
{% extends "base.html" %}
{% block nav %}
	{% include "includes/_nav.html" %}
{% endblock nav %}
{% block main %}
<div class="container">
	<h4>Baixa Log</h4>
	<table>
		<thead>
			<tr>
				<th>Usuario</th>
				<th>Data</th>
				<th>Produto</th>
				<th>Quantidade</th>
				<th>Motivo</th>
			</tr>
		</thead>
		<tbody>
			{%for obj in objects%}
			<tr>
				<td>{{obj.user}}</td>
				<td>{{obj.baixa_data}}</td>
				<td>{{obj.baixa_produto}}</td>
				<td>{{obj.baixa_quantidade}}</td>
				<td>{{obj.baixa_motivo}}</td>
			</tr>
			{%endfor%}
		</tbody>
	</table>
</div>
{% endblock main %}

InventoryManager/baixa/templates/baixa_produto.html
{% extends "base.html" %}
{% block nav %}
	{% include "includes/_nav.html" %}
{% endblock nav %}
{% block main %}
<div class="container">
	<div class="row"></div>
	<div class="card">
		<div class="card-content">
			{%include 'includes/_messages.html'%}
	<form method="post">
	{% csrf_token %}
		<div class="col">
			<h4>Produto: {{produto.produto_nome}}</h4>
			<h5>Quantidade Atual: {{produto.produto_quantidade}}</h5>
		</div>
		<div class="row"></div>
		<div class="col s12 input-field">
			<input type="hidden" name="user" id="id_user" value={{request.user.id}}>
			<select name="baixa_produto" required="" id="id_baixa_produto">
			<option value="{{produto.id}}" selected=""></option>
		</div>
		<div class="col s12 input-field">
			<input type="number" name="baixa_quantidade" required="" id="id_baixa_quantidade">
			<label for="id_baixa_quantidade" class="active">Quantidade:</label>
		</div>
		<div class="row"></div>
		<div class="col s12 input-field">
			<label for="id_baixa_motivo" class="active">Motivo:</label>
			<textarea name="baixa_motivo" cols="40" rows="10" required="" id="id_baixa_motivo"></textarea>
		</div>
		<button class="btn" type="submit">Baixa</button>
	</form>
	</div>
	</div>
</div>
{% endblock main %}

InventoryManager/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
	<title></title>
	<!-- Compiled and minified CSS -->
<style type="text/css">
	.materialert .close-alert{
	    -webkit-appearance: none;
	    border: 0;
	    cursor: pointer;
	    color: inherit;
	    background: 0 0;
	    font-size: 22px;
	    line-height: 1;
	    font-weight: bold;
	    text-shadow: 0 1px 0 rgba(255, 255, 255, .7);
	    filter: alpha(opacity=40);
	    margin-bottom: -5px;
	    position: absolute;
	    top: 16px;
	    right: 5px;
		}
		.materialert.info{
		    background-color: #039be5;
		    color: #fff;
		}
		.materialert.success{
		    background-color: #80cbc4;
		    color: #fff;
		}
		.materialert.error{
		    background-color: #ef5350;
		    color: #fff;
		}
		.materialert.danger{
		    background-color: #c62828;
		    color: #fff;
		}
		.materialert.warning{
		    background-color: #fbc02d;
		    color: #fff;
		}
		.card-image{
			margin-top: 30px;
			margin-bottom: 30px; 
		}
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>

<body>
	
	{% block nav %}
		
	{% endblock nav %}
 
{% block main %}
	
{% endblock main %}

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

InventoryManager/core/templates/includes/_messages.html
{% if messages %}
<br>
{% for message in messages %}

<div class=" center-align materialert {{ message.tags }}">
	<h5>{{ message }}</h5>

</div>
{% endfor %}
{% endif %}

InventoryManager/core/templates/includes/_nav.html
<div class="navbar-fixed">
	<nav class="">
		<div class="nav-wrapper">
			<a href="#" class="brand-logo center">SIM</a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a href="{%url 'produto:list'%}">Produtos</a></li>
				<li><a href="{%url 'baixa:log'%}">Baixa Log</a></li>
				<li><a href="{%url 'entrada:log'%}">Entrada Log</a></li>
			</ul>
		</div>
	</nav>
</div>

InventoryManager/entrada/templates/entrada_log.html
{% extends "base.html" %}
{% block nav %}
	{% include "includes/_nav.html" %}
{% endblock nav %}
{% block main %}
<div class="container">
	<h4>Entrada Log</h4>
	<table>
		<thead>
			<tr>
				<th>Usuario</th>
				<th>Data</th>
				<th>Produto</th>
				<th>Quantidade</th>
				<th>Motivo</th>
			</tr>
		</thead>
		<tbody>
			{%for obj in objects%}
			<tr>
				<td>{{obj.user}}</td>
				<td>{{obj.entrada_data}}</td>
				<td>{{obj.entrada_produto}}</td>
				<td>{{obj.entrada_quantidade}}</td>
				<td>{{obj.entrada_motivo}}</td>
			</tr>
			{%endfor%}
		</tbody>
	</table>
</div>
{% endblock main %}

InventoryManager/entrada/templates/entrada_produto.html
{% extends "base.html" %}
{% block nav %}
	{% include "includes/_nav.html" %}
{% endblock nav %}
{% block main %}
<div class="container">
	<div class="row"></div>
	<div class="card">
		<div class="card-content">
			{%include 'includes/_messages.html'%}
	<form method="post">
	{% csrf_token %}
		<div class="col">
			<h4>Produto: {{produto.produto_nome}}</h4>
			<h5>Quantidade Atual: {{produto.produto_quantidade}}</h5>
		</div>
		<div class="row"></div>
		<div class="col s12 input-field">
			<input type="hidden" name="user" id="id_user" value={{request.user.id}}>
			<select name="entrada_produto" required="" id="id_entrada_produto">
			<option value="{{produto.id}}" selected=""></option>
		</div>
		<div class="col s12 input-field">
			<input type="number" name="entrada_quantidade" required="" id="id_entrada_quantidade">
			<label for="id_entrada_quantidade" class="active">Quantidade:</label>
		</div>
		<div class="row"></div>
		<div class="col s12 input-field">
			<label for="id_entrada_motivo" class="active">Motivo:</label>
			<textarea name="entrada_motivo" cols="40" rows="10" required="" id="id_entrada_motivo"></textarea>
		</div>
		<button class="btn" type="submit">Entrada</button>
	</form>
	</div>
	</div>
</div>
{% endblock main %}

InventoryManager/produto/templates/produto_list.html
{%extends 'base.html'%}

{% block nav %}
	{% include "includes/_nav.html" %}
{% endblock nav %}
{% block main %}
<div class="container">
	{%include 'includes/_messages.html'%}
	<div class="col s12 m12 l12">
		<div class="row">
			{% for obj in objects  %}
				<div class="col s12 m4">
					<div class="card">
						<div class="card-image">
							<img style="height: 300px;width: 100%;" class="img-responsive" src="{{obj.produto_imagem.url}}">
						</div>
						<div class="card-content">
							{% if obj.produto_preco %}
								<h4><span>$</span>{{obj.produto_preco}}</h4>
							{% endif %}
							
							<span class="card-title black-text">{{obj.produto_nome}}</span>
							<h5>Em estoque: {{obj.produto_quantidade}}</h5>
							{% if obj.produto_descricao %}
								<p>{{obj.produto_descricao|slice:200}}...</p>
							{% endif %}
							
						</div>
						<div class="card-action">
							<div class="row">
							<div class="col m4">
								<a href="{%url 'entrada:entrada' obj.id%}"><button class="btn">Entrada</button></a>
							</div>
							<div class="col m4 right">
								<a href="{%url 'baixa:baixa' obj.id%}"><button class="btn">Baixa</button></a>
							</div>
							</div>
							
						</div>
					</div>
				</div>	
			{% endfor %}
		</div>
	</div>
</div>
{% endblock main %}